#!/bin/bash
cp -R developer/bin ./
cp developer/env/.env .
cp developer/docker-compose.dev.yml docker-compose.yml
cp developer/auth.json .
cp developer/env.php.example .
cp developer/config.php.example .

# Setup
source developer/env/magento.env
source .env
source bin/setup